CREATE DATABASE IF NOT EXISTS game_db
    CHARACTER SET utf8mb4
    COLLATE utf8mb4_unicode_ci;

USE game_db;

CREATE TABLE IF NOT EXISTS scores (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    score INT UNSIGNED NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_score_range CHECK (score BETWEEN 0 AND 100000)
);